### ISSUE TITLE
[1.21.1] Crash on start-up without Curios API Continuation...

### ISSUE THREAD

**Issue by squiig** [ofek2608/crafting_on_a_stick#16]
Crash report: https://pastebin.com/pHNsfqX5

Playing on FTB Evolution. In the recent 1.6 update they removed Curios API Continuation, so COAS could be bugged in another way.

**Comment by Peca21** [comment]
Same here, custom modpack
https://pastebin.com/QJAu6ivg

EDIT: https://github.com/OfekN-mods/crafting-on-a-stick/issues/13#issuecomment-2212659179

EDIT EDIT: I removed curious and replaced it with Adorned, still the same crash.

**Comment by Peca21** [comment]
Update:
I removed crafting on a stick from my modpack, then useful backpacks crashed with a similar error, then I removed useful backpacks, but now metal barrels is crashing. I removed metal barrels and MC started. I returned both backpacks and crafting on a stick and modpack started fine.
It looks like some other mods are crashing and for some reason making other mods crash.

https://github.com/Tfarcenim/MetalBarrels/issues/33

**Comment by Ashley123477** [comment]
same issue with Curios API

java.lang.NullPointerException: Cannot read field "OPEN_CURIOS_KEY" because "com.ofekn.crafting_on_a_stick.COASKeyMappings.keys" is null
	at TRANSFORMER/crafting_on_a_stick@1.21.0.1/com.ofekn.crafting_on_a_stick.COASKeyMappings$ForgeEvents.event(COASKeyMappings.java:26)

**Comment by ArsiTheFox** [comment]
> same issue with Curios API
> 
> java.lang.NullPointerException: Cannot read field "OPEN_CURIOS_KEY" because "com.ofekn.crafting_on_a_stick.COASKeyMappings.keys" is null at TRANSFORMER/crafting_on_a_stick@1.21.0.1/com.ofekn.crafting_on_a_stick.COASKeyMappings$ForgeEvents.event(COASKeyMappings.java:26)

If your pack has Croptopia installed make sure EpheroLib is included.... it turns out that somehow broke the loading even though it said it was an issue with Crafting on a stick

**Comment by ofek2608** [comment]
another mod is causing the loading order to be incorrect.
anyways, in the newer update it shouldn't happen
